const defaultSoftware = [];
let software = [...defaultSoftware];
let editingIndex = -1;
const categories = [{name:'效率办公',icon:'⌘',color:'#e45738',bg:'#fff0ea'},{name:'开发工具',icon:'</>',color:'#456fe2',bg:'#edf1ff'},{name:'设计创作',icon:'✦',color:'#b44bc8',bg:'#fbedff'},{name:'影音播放',icon:'▶',color:'#178db5',bg:'#e8f7fc'},{name:'实用工具',icon:'⌁',color:'#118a72',bg:'#e8f8f2'},{name:'游戏娱乐',icon:'◇',color:'#df7424',bg:'#fff3e7'},{name:'安全隐私',icon:'▣',color:'#6978aa',bg:'#eff1f9'}];
let selectedCategory='', selectedDevice='', query='', sort='latest';
const deviceMatchers={电脑软件:/windows|mac|linux|电脑|桌面/i,手机软件:/android|ios|iphone|ipad|手机/i,电视软件:/tv|电视|android tv|智能电视/i};
const $ = s => document.querySelector(s);
function matches(item){ const text=`${item.name} ${item.category} ${item.desc} ${item.platform}`.toLowerCase(); return (!selectedCategory || item.category===selectedCategory) && (!selectedDevice || deviceMatchers[selectedDevice]?.test(text)) && (!query || text.includes(query.toLowerCase())); }
function appIcon(item){ return `<span class="app-icon" style="--app-color:${item.color}">${item.icon}</span>`; }
function renderCategories(){ $('#categoryGrid').innerHTML=categories.map(c=>{const count=software.filter(s=>s.category===c.name).length;return `<button class="category-button ${selectedCategory===c.name?'active':''}" data-category="${c.name}" style="--category:${c.color};--icon-bg:${c.bg}"><span class="category-icon">${c.icon}</span><span class="category-name">${c.name}</span><span class="category-count">${count} 款软件</span></button>`}).join(''); document.querySelectorAll('[data-category]').forEach(b=>b.onclick=()=>{selectedCategory=selectedCategory===b.dataset.category?'':b.dataset.category; render();}); }
function renderSoftware(){ let items=software.filter(matches); items.sort((a,b)=>sort==='popular'?b.downloads-a.downloads:sort==='name'?a.name.localeCompare(b.name):b.date.localeCompare(a.date)); $('#softwareGrid').innerHTML=items.map(item=>`<button class="software-card" data-app="${item.name}">${appIcon(item)}<span class="app-info"><span class="app-name">${item.name}<small class="platform">${item.platform}</small></span><span class="app-desc">${item.desc}</span><span class="app-meta"><span>${item.category}</span><span>${item.version}</span><span>${item.date}</span></span></span></button>`).join(''); $('#emptyState').hidden=items.length>0; $('#softwareTitle').textContent=selectedDevice || selectedCategory || (query?'搜索结果':'最新收录'); const filter=$('#activeFilter'); filter.hidden=!(selectedCategory||selectedDevice||query); filter.querySelector('span').textContent=selectedDevice||selectedCategory||`“${query}”`; document.querySelectorAll('[data-app]').forEach(b=>b.onclick=()=>openDialog(software.find(x=>x.name===b.dataset.app))); }
function renderPopular(){ $('#popularList').innerHTML=[...software].sort((a,b)=>b.downloads-a.downloads).slice(0,3).map((item,i)=>`<div class="popular-card"><span class="popular-rank">0${i+1}</span>${appIcon(item)}<span class="popular-copy"><strong>${item.name}</strong><small>${item.desc}</small></span></div>`).join(''); }
function openDialog(item){ $('#dialogContent').innerHTML=`<div class="dialog-top">${appIcon(item)}<div><h3 class="dialog-title">${item.name}</h3><span class="platform">${item.platform}</span></div></div><p class="dialog-summary">${item.desc}</p><div class="detail-grid"><div class="detail-item"><small>最新版本</small><strong>${item.version}</strong></div><div class="detail-item"><small>软件分类</small><strong>${item.category}</strong></div><div class="detail-item"><small>收录日期</small><strong>${item.date}</strong></div><div class="detail-item"><small>关注人数</small><strong>${item.downloads.toLocaleString()}</strong></div></div><a class="download-link" href="${item.url}" target="_blank" rel="noopener">前往官方下载 ↗</a>`; $('#softwareDialog').showModal(); }
function render(){ renderCategories(); renderSoftware(); }
$('#searchInput').addEventListener('input',e=>{query=e.target.value.trim();render();}); $('#sortSelect').onchange=e=>{sort=e.target.value;renderSoftware();}; $('#clearFilter').onclick=()=>{selectedCategory='';selectedDevice='';query='';$('#searchInput').value='';render();}; $('#dialogClose').onclick=()=>$('#softwareDialog').close(); $('#themeButton').onclick=()=>{document.body.classList.toggle('dark'); localStorage.setItem('ruanji-theme',document.body.classList.contains('dark')?'dark':'light');}; document.addEventListener('keydown',e=>{if(e.key==='/'&&!['INPUT','TEXTAREA'].includes(document.activeElement.tagName)){e.preventDefault();$('#searchInput').focus();}});
document.querySelectorAll('[data-device]').forEach(link=>link.onclick=()=>{selectedDevice=selectedDevice===link.dataset.device?'':link.dataset.device; selectedCategory=''; render();});

const isCloudMode=location.protocol.startsWith('http');
function refresh(){ $('#softwareCount').textContent=software.length; render(); renderPopular(); renderAdminList(); }
async function loadSoftware(){ if(!isCloudMode){ software=JSON.parse(localStorage.getItem('ruanji-software')||'null')||[...defaultSoftware]; refresh(); return; } try{ const response=await fetch('/api/software'); if(!response.ok)throw new Error(); const custom=await response.json(); software=[...custom,...defaultSoftware]; refresh(); }catch{ console.warn('数据库尚未配置，正在显示内置软件。'); } }
function checkLocalPassword(value){ const saved=localStorage.getItem('ruanji-admin-password'); if(!saved){ localStorage.setItem('ruanji-admin-password',value); return true; } return saved===value; }
function resetAdminForm(password=''){ editingIndex=-1; $('#adminForm').reset(); $('#adminPassword').value=password; $('#softwareIcon').value='S'; $('#softwareColor').value='#4f46e5'; $('#adminSubmit').textContent='添加软件'; $('#cancelEdit').hidden=true; }
function startEdit(index){ const item=software[index]; editingIndex=index; $('#softwareName').value=item.name; $('#softwareCategory').value=item.category; $('#softwarePlatform').value=item.platform; $('#softwareVersion').value=item.version; $('#softwareUrl').value=item.url; $('#softwareDesc').value=item.desc; $('#softwareIcon').value=item.icon||'S'; $('#softwareColor').value=item.color||'#4f46e5'; $('#adminSubmit').textContent='保存修改'; $('#cancelEdit').hidden=false; $('#softwareName').focus(); }
function renderAdminList(){ $('#adminList').innerHTML='<h4>软件列表</h4>'+software.map((item,index)=>`<div><span>${item.name}</span>${item.id||!isCloudMode?`<span class="admin-item-actions"><button type="button" data-edit="${index}">修改</button><button type="button" data-delete="${index}">删除</button></span>`:'<small>内置</small>'}</div>`).join(''); document.querySelectorAll('[data-edit]').forEach(button=>button.onclick=()=>startEdit(Number(button.dataset.edit))); document.querySelectorAll('[data-delete]').forEach(button=>button.onclick=async()=>{ const index=Number(button.dataset.delete),item=software[index],password=$('#adminPassword').value; if(!password){ alert('请输入管理密码'); return; } if(!confirm('确定删除这个软件吗？'))return; if(isCloudMode){ const response=await fetch(`/api/software?id=${item.id}`,{method:'DELETE',headers:{'X-Admin-Password':password}}); if(!response.ok){ const result=await response.json(); alert(result.error||'删除失败'); return; } await loadSoftware(); }else{ if(!checkLocalPassword(password)){ alert('管理密码错误'); return; } software.splice(index,1); localStorage.setItem('ruanji-software',JSON.stringify(software)); refresh(); } if(editingIndex===index)resetAdminForm(password); }); }
$('#softwareCategory').innerHTML=categories.map(c=>`<option value="${c.name}">${c.name}</option>`).join('');
$('#adminButton').onclick=()=>{ renderAdminList(); $('#adminDialog').showModal(); };
$('#adminClose').onclick=()=>$('#adminDialog').close();
$('#cancelEdit').onclick=()=>resetAdminForm($('#adminPassword').value);
$('#adminForm').onsubmit=async e=>{ e.preventDefault(); const password=$('#adminPassword').value,item={name:$('#softwareName').value.trim(),icon:$('#softwareIcon').value.trim()||'S',color:$('#softwareColor').value,category:$('#softwareCategory').value,platform:$('#softwarePlatform').value.trim(),version:$('#softwareVersion').value.trim(),date:new Date().toISOString().slice(0,10),downloads:0,desc:$('#softwareDesc').value.trim(),url:$('#softwareUrl').value.trim()},isEditing=editingIndex>=0,current=software[editingIndex]; if(isCloudMode){ const response=await fetch(isEditing?`/api/software?id=${current.id}`:'/api/software',{method:isEditing?'PUT':'POST',headers:{'Content-Type':'application/json','X-Admin-Password':password},body:JSON.stringify(item)}); const result=await response.json(); if(!response.ok){ alert(result.error||(isEditing?'修改失败':'添加失败')); return; } await loadSoftware(); }else{ if(!checkLocalPassword(password)){ alert('管理密码错误'); return; } if(isEditing)software[editingIndex]={...current,...item,date:current.date}; else software.unshift(item); localStorage.setItem('ruanji-software',JSON.stringify(software)); refresh(); } resetAdminForm(password); alert(isEditing?'软件修改成功':'软件添加成功'); };
if(localStorage.getItem('ruanji-theme')==='dark')document.body.classList.add('dark'); refresh(); loadSoftware();
