const defaultSoftware = [
  { name:'Obsidian', icon:'◈', color:'#7865e8', category:'效率办公', platform:'Win / Mac', version:'1.8.10', date:'2026-07-24', downloads:12840, desc:'本地优先的知识库，将零散想法连接成属于你的第二大脑。', url:'https://obsidian.md/download' },
  { name:'Raycast', icon:'✦', color:'#ff5c58', category:'效率办公', platform:'macOS', version:'1.88.0', date:'2026-07-21', downloads:9620, desc:'更快的启动器、命令中心和自动化工具，让每次操作都更顺手。', url:'https://www.raycast.com/' },
  { name:'PotPlayer', icon:'▶', color:'#28a8ea', category:'影音播放', platform:'Windows', version:'1.7.22619', date:'2026-07-19', downloads:24580, desc:'轻巧强大的本地播放器，支持丰富格式与细致的播放控制。', url:'https://potplayer.daum.net/' },
  { name:'Figma', icon:'F', color:'#f24e1e', category:'设计创作', platform:'Web / Win', version:'在线版', date:'2026-07-16', downloads:18870, desc:'多人实时协作的界面设计工具，从灵感到交付都在同一个空间完成。', url:'https://www.figma.com/' },
  { name:'LocalSend', icon:'↗', color:'#00a6a6', category:'实用工具', platform:'全平台', version:'1.17.0', date:'2026-07-14', downloads:11200, desc:'无需联网的局域网文件传输工具，简单、安全且没有大小限制。', url:'https://localsend.org/' },
  { name:'Zed', icon:'Z', color:'#0749a9', category:'开发工具', platform:'Mac / Linux', version:'0.196.0', date:'2026-07-12', downloads:7540, desc:'为协作而生的高性能代码编辑器，拥有流畅的原生体验。', url:'https://zed.dev/' },
  { name:'1Password', icon:'1', color:'#2775e8', category:'安全隐私', platform:'全平台', version:'8.11.8', date:'2026-07-09', downloads:13620, desc:'安全保存密码、密钥和重要资料，跨设备同步且随时可用。', url:'https://1password.com/downloads/' },
  { name:'Steam', icon:'◆', color:'#1b2838', category:'游戏娱乐', platform:'Win / Mac', version:'最新版', date:'2026-07-06', downloads:31890, desc:'全球游戏玩家的数字发行平台，发现、购买并管理你的游戏库。', url:'https://store.steampowered.com/about/' },
  { name:'Notion', icon:'N', color:'#242424', category:'效率办公', platform:'全平台', version:'4.19.0', date:'2026-07-03', downloads:27860, desc:'把文档、项目、知识库和协作都组织在一个灵活的工作空间。', url:'https://www.notion.so/desktop' }
];
let software = [...defaultSoftware];
const categories = [{name:'效率办公',icon:'⌘',color:'#e45738',bg:'#fff0ea'},{name:'开发工具',icon:'</>',color:'#456fe2',bg:'#edf1ff'},{name:'设计创作',icon:'✦',color:'#b44bc8',bg:'#fbedff'},{name:'影音播放',icon:'▶',color:'#178db5',bg:'#e8f7fc'},{name:'实用工具',icon:'⌁',color:'#118a72',bg:'#e8f8f2'},{name:'游戏娱乐',icon:'◇',color:'#df7424',bg:'#fff3e7'},{name:'安全隐私',icon:'▣',color:'#6978aa',bg:'#eff1f9'}];
let selectedCategory='', query='', sort='latest';
const $ = s => document.querySelector(s);
function matches(item){ const text=`${item.name} ${item.category} ${item.desc} ${item.platform}`.toLowerCase(); return (!selectedCategory || item.category===selectedCategory) && (!query || text.includes(query.toLowerCase())); }
function appIcon(item){ return `<span class="app-icon" style="--app-color:${item.color}">${item.icon}</span>`; }
function renderCategories(){ $('#categoryGrid').innerHTML=categories.map(c=>{const count=software.filter(s=>s.category===c.name).length;return `<button class="category-button ${selectedCategory===c.name?'active':''}" data-category="${c.name}" style="--category:${c.color};--icon-bg:${c.bg}"><span class="category-icon">${c.icon}</span><span class="category-name">${c.name}</span><span class="category-count">${count} 款软件</span></button>`}).join(''); document.querySelectorAll('[data-category]').forEach(b=>b.onclick=()=>{selectedCategory=selectedCategory===b.dataset.category?'':b.dataset.category; render();}); }
function renderSoftware(){ let items=software.filter(matches); items.sort((a,b)=>sort==='popular'?b.downloads-a.downloads:sort==='name'?a.name.localeCompare(b.name):b.date.localeCompare(a.date)); $('#softwareGrid').innerHTML=items.map(item=>`<button class="software-card" data-app="${item.name}">${appIcon(item)}<span class="app-info"><span class="app-name">${item.name}<small class="platform">${item.platform}</small></span><span class="app-desc">${item.desc}</span><span class="app-meta"><span>${item.category}</span><span>${item.version}</span><span>${item.date}</span></span></span></button>`).join(''); $('#emptyState').hidden=items.length>0; $('#softwareTitle').textContent=selectedCategory || (query?'搜索结果':'最新收录'); const filter=$('#activeFilter'); filter.hidden=!(selectedCategory||query); filter.querySelector('span').textContent=selectedCategory||`“${query}”`; document.querySelectorAll('[data-app]').forEach(b=>b.onclick=()=>openDialog(software.find(x=>x.name===b.dataset.app))); }
function renderPopular(){ $('#popularList').innerHTML=[...software].sort((a,b)=>b.downloads-a.downloads).slice(0,3).map((item,i)=>`<div class="popular-card"><span class="popular-rank">0${i+1}</span>${appIcon(item)}<span class="popular-copy"><strong>${item.name}</strong><small>${item.desc}</small></span></div>`).join(''); }
function openDialog(item){ $('#dialogContent').innerHTML=`<div class="dialog-top">${appIcon(item)}<div><h3 class="dialog-title">${item.name}</h3><span class="platform">${item.platform}</span></div></div><p class="dialog-summary">${item.desc}</p><div class="detail-grid"><div class="detail-item"><small>最新版本</small><strong>${item.version}</strong></div><div class="detail-item"><small>软件分类</small><strong>${item.category}</strong></div><div class="detail-item"><small>收录日期</small><strong>${item.date}</strong></div><div class="detail-item"><small>关注人数</small><strong>${item.downloads.toLocaleString()}</strong></div></div><a class="download-link" href="${item.url}" target="_blank" rel="noopener">前往官方下载 ↗</a>`; $('#softwareDialog').showModal(); }
function render(){ renderCategories(); renderSoftware(); }
$('#searchInput').addEventListener('input',e=>{query=e.target.value.trim();render();}); $('#sortSelect').onchange=e=>{sort=e.target.value;renderSoftware();}; $('#clearFilter').onclick=()=>{selectedCategory='';query='';$('#searchInput').value='';render();}; $('#dialogClose').onclick=()=>$('#softwareDialog').close(); $('#themeButton').onclick=()=>{document.body.classList.toggle('dark'); localStorage.setItem('ruanji-theme',document.body.classList.contains('dark')?'dark':'light');}; document.addEventListener('keydown',e=>{if(e.key==='/'&&!['INPUT','TEXTAREA'].includes(document.activeElement.tagName)){e.preventDefault();$('#searchInput').focus();}});

const isCloudMode=location.protocol.startsWith('http');
function refresh(){ $('#softwareCount').textContent=software.length; render(); renderPopular(); renderAdminList(); }
async function loadSoftware(){ if(!isCloudMode){ software=JSON.parse(localStorage.getItem('ruanji-software')||'null')||[...defaultSoftware]; refresh(); return; } try{ const response=await fetch('/api/software'); if(!response.ok)throw new Error(); const custom=await response.json(); software=[...custom,...defaultSoftware]; refresh(); }catch{ console.warn('数据库尚未配置，正在显示内置软件。'); } }
function checkLocalPassword(value){ const saved=localStorage.getItem('ruanji-admin-password'); if(!saved){ localStorage.setItem('ruanji-admin-password',value); return true; } return saved===value; }
function renderAdminList(){ $('#adminList').innerHTML='<h4>软件列表</h4>'+software.map((item,index)=>`<div><span>${item.name}</span>${item.id||!isCloudMode?`<button type="button" data-delete="${index}">删除</button>`:'<small>内置</small>'}</div>`).join(''); document.querySelectorAll('[data-delete]').forEach(button=>button.onclick=async()=>{ const index=Number(button.dataset.delete),item=software[index],password=$('#adminPassword').value; if(!password){ alert('请输入管理密码'); return; } if(!confirm('确定删除这个软件吗？'))return; if(isCloudMode){ const response=await fetch(`/api/software?id=${item.id}`,{method:'DELETE',headers:{'X-Admin-Password':password}}); if(!response.ok){ const result=await response.json(); alert(result.error||'删除失败'); return; } await loadSoftware(); }else{ if(!checkLocalPassword(password)){ alert('管理密码错误'); return; } software.splice(index,1); localStorage.setItem('ruanji-software',JSON.stringify(software)); refresh(); } }); }
$('#softwareCategory').innerHTML=categories.map(c=>`<option value="${c.name}">${c.name}</option>`).join('');
$('#adminButton').onclick=()=>{ renderAdminList(); $('#adminDialog').showModal(); };
$('#adminClose').onclick=()=>$('#adminDialog').close();
$('#adminForm').onsubmit=async e=>{ e.preventDefault(); const password=$('#adminPassword').value,item={name:$('#softwareName').value.trim(),icon:$('#softwareIcon').value.trim()||'S',color:$('#softwareColor').value,category:$('#softwareCategory').value,platform:$('#softwarePlatform').value.trim(),version:$('#softwareVersion').value.trim(),date:new Date().toISOString().slice(0,10),downloads:0,desc:$('#softwareDesc').value.trim(),url:$('#softwareUrl').value.trim()}; if(isCloudMode){ const response=await fetch('/api/software',{method:'POST',headers:{'Content-Type':'application/json','X-Admin-Password':password},body:JSON.stringify(item)}); const result=await response.json(); if(!response.ok){ alert(result.error||'添加失败'); return; } await loadSoftware(); }else{ if(!checkLocalPassword(password)){ alert('管理密码错误'); return; } software.unshift(item); localStorage.setItem('ruanji-software',JSON.stringify(software)); refresh(); } e.target.reset(); $('#adminPassword').value=password; $('#softwareColor').value='#4f46e5'; alert('软件添加成功'); };
if(localStorage.getItem('ruanji-theme')==='dark')document.body.classList.add('dark'); refresh(); loadSoftware();
